### ISSUE TITLE
Angular styleguide

### ISSUE THREAD

**Issue by verebelyin** [Ismaestro/angular4-example-app#15]
Hi!

I bumped into this project while I was looking for an example app that is following the the official [Angular styleguide](https://angular.io/guide/styleguide).

I see that you are trying to follow the guidelines, but there is one thing, which is against it. Specifically against this [point](https://angular.io/guide/styleguide#shared-feature-module):
```Avoid providing services in shared modules. Services are usually singletons that are provided once for the entire application or in a particular feature module.```

Is it intentional that you have the `src/app/shared/services/` folder, and services in it, which are used throughout the app?

According to the [Angular styleguide](https://angular.io/guide/styleguide#core-feature-module), it should be placed under `src/app/core`.

Thanks,
Norbert

**Comment by Ismaestro** [comment]
Hi Norbert!

You are completely right, so I've made some changes.

You can see them [here](https://github.com/Ismaestro/angular4-example-app/commit/ae53c7847e9df48e1036b61a1e90c32cbaa2e956).

Thanks and best regards.

**Comment by verebelyin** [comment]
Thank you for the modification, now it seems better :)

Yes, I agree, that in some cases it's needed, but it will be usually coming from one of the components.

In this example, it's the `HeroService`, that is placed in the `app/heroes/shared`, indicating it's a shared service, but belongs to the Hero component. And it is imported in the `SharedModule` as a global provider, to make it available for everyone.
