### ISSUE TITLE
Importing Material Module

### ISSUE THREAD

**Issue by bilel-noomene** [Ismaestro/angular4-example-app#3]
I want to know why import the MateriaModule module both into CoreModule and into AppModule? Why not add it to the CoreBundle module exports  and remove it from AppBundle?
Thanks

**Comment by Ismaestro** [comment]
Hello @bilel-noomene,
CoreModule only exports components from it's own module, and the main reason to use exports is to allow other modules to import what you are exporting. 
So, MaterialModule should be imported in every module that use angular material components. You have more info [here](https://material.angular.io/guide/getting-started#step-3-import-the-component-modules).

**Comment by Ismaestro** [comment]
@bilel-noomene thinking about this, I've made a change to only import MaterialModule in one point (SharedModule), and export it in that module because every module should import SharedModule...

**Comment by bilel-noomene** [comment]
Thank you @Ismaestro. 
In this case, will it be more consistent to place MaterialModule under the shared folder?

**Comment by Ismaestro** [comment]
@bilel-noomene Of course, [done](https://github.com/Ismaestro/angular4-example-app/commit/86c9894124a444865b612fe5ee4010f7023e4478).
