### ISSUE TITLE
Not able to run this application

### ISSUE THREAD

**Issue by Bichitra73** [Ismaestro/angular4-example-app#5]
Hi  I am new to angular , downloaded this source code,  then  installed cli using npm install -g  @angular/cli and then try to use  ng command serve, getting build error angular-modules not found.. do i need to install npm in the same project folder?  any suggestion how to make  run  this application

**Comment by Ismaestro** [comment]
@Bichitra73 Hi, you should be able to run the app just having angular-cli at least v1.0.0 installed, node v7.10.0 and npm v4.2.0. Please check this versions (in this order):
```
node -v
npm -v
ng -v
```
If any version is not up to date, upgrade it and for angular-cli, [follow this instructions](https://github.com/angular/angular-cli#updating-angular-cli).

And please, provide more info pasting here the errors that you are getting.

**Comment by Ismaestro** [comment]
In addition, I've upgraded the documentation.

**Comment by Bichitra73** [comment]
Hi ,

Should I run npm install -g @angular/cli or  npm install -g  angular-cli.. as per documentation @angular\cli is latest for angular 4 .. do I need to install cli in project folder also? will it take from global folder.

 I installed  node -v = 7.10.0 , npm  v = 4.2.0  wating for your reply to install cli which command

**Comment by Ismaestro** [comment]
Hi @Bichitra73,

if you have that versions, now you only have to install all the modules with:

`npm install` and then run `npm start`

(be sure to remove node_modules folder first)

Doing this, tell me if something goes wrong.

**Comment by Bichitra73** [comment]
Hi 
My first question is which command should I run **nmp install @angular/cli** or **nmp install  angular-cli**
2nd question in which folder I should run npm install to install modules.. should I run as global like
npm install -g or inside aoolication folder npm install so it will install all modules. where should I delete  node_modules modules.
appreciated your help..
Thanks 
Bichitra

**Comment by Ismaestro** [comment]
Only **nmp install** in the folder **where is located package.json**. To remove node_modules first, this folder is in the same path as package.json. If you don't see it, do nothing.

BR

**Comment by Bichitra73** [comment]
Thank you it worked... 
Can I ask  one question not related this project but related angular 4

**Comment by Ismaestro** [comment]
Yes, of course, but not in this one, first open a new issue please.

Thanks

**Comment by Bichitra73** [comment]
Hi ,
if i would like to  use ng command by installing npm install -g @angular/cli and using ng command ng serve to run this project.  when i install the above command it install with different version node-modules in appdata folder. then how do I  resolve dependency to this project running @angular/cli ng 

appreciated for your help
