### ISSUE TITLE
running this project using ng command

### ISSUE THREAD

**Issue by Bichitra73** [Ismaestro/angular4-example-app#7]
Hi ,
if i would like to use ng command by installing npm install -g and using ng command ng serve to run this project. when i install the above command it install with different version node-modules in appdata folder. then how do I resolve dependency to this project running ng

appreciated for your help

**Comment by Ismaestro** [comment]
Hi!
You have to install angular-cli like this:
`npm install -g @angular/cli`

Then, you can run ng serve or whatever you like. See [this](https://github.com/angular/angular-cli#installation).

**Comment by Bichitra73** [comment]
I did the same way , but  dependency not resolved
getting error 
C:\Working\Ang-Test\angular4-example-app-master-CLI>ng serve
**node_modules appears empty, you may need to run `npm install`**
![untitled](https://user-images.githubusercontent.com/18617824/28376715-d4d4024a-6c78-11e7-870f-e1fa7b2523a4.png)
..

**Comment by Ismaestro** [comment]
Thats because you didn't install dependencies. First you have to do `npm install` like the message says. The order, the first time to install is:

1. `npm install -g @angular/cli`
2. `npm install`

Then, every time you want to install a project just run **npm install**.

**Comment by Bichitra73** [comment]
How to upgrade  angular 4.3.0 from 4.2.4
